### ISSUE TITLE
Error connect ETIMEDOUT - whats this for a Issus??

### ISSUE THREAD

**Issue by Gremly84** [ashleykleynhans/raid-scanner#2]
![unbenannt](https://user-images.githubusercontent.com/29757937/27994341-186911ea-64bc-11e7-8f80-55bf8204bb94.JPG)

**Comment by ashleykleynhans** [comment]
Don't waste my time logging issues that aren't even related to the code. Surely you must know by now that the hashing servers have issues, go bother them, is is not an issue with the code.
